name: Build and Test
on: 
  pull_request:
    branches: [master, develop]
  push:
    branches: [master, develop]
      
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
      - run: dotnet build
  tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Tests
        uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
      - run: dotnet test
    
      
