name: Deploy

on:
  workflow_dispatch:
    inputs:
      everionment:
        type: choice
        description: Deploy
        options: 
        - Dev
        - Staging
        - Prod     

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "${{ github.event.inputs.everionment }}"
